---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect-csm
  namespace: ccloud
  annotations:
    platform.confluent.io/pod-overlay-configmap-name: csm-enabled
spec:
  replicas: 1
  spec:
  podTemplate:
    probe:
      liveness:
      readiness:
  image:
    application: confluentinc/cp-server-connect:8.1.0
    init: confluentinc/confluent-init-container:3.1.0
  configOverrides:
    server:
      - 'response.http.headers.config="add Cache-Control: no-cache, no-store, must-revalidate", add X-XSS-Protection: 1; mode=block, add Strict-Transport-Security: max-age=31536000; includeSubDomains, add X-Content-Type-Options: nosniff'
      - sni.host.check.enabled=false
  license:
    globalLicense: true
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: confluentHub
        confluentHub:
          - name: kafka-connect-datagen
            owner: confluentinc
            version: 0.6.0
  dependencies:
    kafka:
      bootstrapEndpoint: localhost:30001
      authentication:
        type: plain
        jaasConfig:
          secretRef: ccloud-credentials
      tls:
        enabled: false
    schemaRegistry:
      url: https://psrc-8vyvr.eu-central-1.aws.confluent.cloud
      authentication:
        type: basic
        basic:
          secretRef: ccloud-sr-credentials