apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
  annotations:
    platform.confluent.io/pod-overlay-configmap-name: csm-enabled
spec:
  replicas: 1
  image:
    application: confluentinc/cp-ksqldb-server:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  internalTopicReplicationFactor: 3
  dataVolumeCapacity: 10Gi
  podTemplate:
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  dependencies:
    kafka:
      bootstrapEndpoint: localhost:30001
      authentication:
        type: plain
        jaasConfig:
          secretRef: ccloud-credentials
      tls:
        enabled: false
    schemaRegistry:
      url: https://psrc-8vyvr.eu-central-1.aws.confluent.cloud
      authentication:
        type: basic
        basic:
          secretRef: ccloud-sr-credentials