---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-zookeeper:7.2.0
    init: confluentinc/confluent-init-container:2.4.0
  license:
    globalLicense: true
  dataVolumeCapacity: 1Gi
  logVolumeCapacity: 1Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.2.0
    init: confluentinc/confluent-init-container:2.4.0
  license:
    globalLicense: true
  dataVolumeCapacity: 1Gi
  listeners:
    external:
      authentication:
        type: ldap
  identityProvider:
    type: ldap
    ldap:
      address: ldap://10.0.0.5:389
      authentication:
        type: simple
        simple:
          secretRef: credentials
      configurations:
        groupSearchBase: ou=Groups,ou=Kafka,dc=schmitzi,dc=net
        groupObjectClass: posixGroup
        groupSearchScope: 2
        groupNameAttribute: cn
        groupMemberAttribute: member
        groupMemberAttributePattern: cn=(.*),ou=Groups,ou=Kafka,dc=schmitzi,dc=net
        userSearchScope: 2
        userNameAttribute: uid
        userObjectClass: posixAccount
        userSearchBase: ou=Users,ou=Kafka,dc=schmitzi,dc=net
  metricReporter:
    enabled: true
  configOverrides:
    server:
      - offsets.topic.replication.factor=1
      - transaction.state.log.replication.factor=1
      - confluent.license.topic.replication.factor=1
      - confluent.metadata.topic.replication.factor=1
      - confluent.balancer.topic.replication.factor=1
      - confluent.metrics.reporter.topic.replicas=1
      - confluent.security.event.logger.exporter.kafka.topic.replicas=1
---
