apiVersion: v1
kind: Pod
metadata:
  name: kcat
  namespace: confluent
spec:
  containers:
  - name: cp-kcat
    image: confluentinc/cp-kcat:7.2.2
    command: ['sh', '-c', 'kcat -F /mnt/kcat.conf -L']
    # command: ['sh', '-c', 'tail -f /dev/null']
    volumeMounts:
      - name: kcat-config
        mountPath: /mnt
        readOnly: true
  volumes:
    - name: kcat-config 
      secret:
        secretName: kcat-config
