apiVersion: v1
kind: ConfigMap
metadata:
  name: kcat-config
  namespace: confluent
data:
  kcat.conf: |
    bootstrap.servers=kafka.confluent.svc.cluster.local:9092
    security.protocol=SASL_PLAINTEXT
    sasl.mechanisms=PLAIN
    sasl.username=kafka
    sasl.password=kafka123
---
apiVersion: v1
kind: Pod
metadata:
  name: kcat
  namespace: confluent
spec:
  containers:
  - name: cp-kcat
    image: confluentinc/cp-kcat:7.2.2
    command: ['sh', '-c', 'kcat -F /mnt/kcat.conf -L']
    # command: ['sh', '-c', 'tail -f /dev/null']
    volumeMounts:
      - name: kcat-config
        mountPath: /mnt
        readOnly: true
  volumes:
    - name: kcat-config 
      configMap:
        name: kcat-config
  restartPolicy: Never
---
