---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: controlcenter-user
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: default
  principal:
    name: c3
    type: user
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: controlcenter-group
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: default
  principal:
    name: c3users
    type: group
  role: Operator
---
