apiVersion: platform.confluent.io/v1beta1
kind: SchemaExporter
metadata:
  name: schemaexporter
  namespace: confluent
spec:
  sourceCluster:
  #   schemaRegistryClusterRef:
  #     name: schemaregistry
  #     namespace: confluent
  destinationCluster:
    schemaRegistryRest:
      endpoint: http://schemaregistry.confluent-target.svc.cluster.local:8081
  # contextType: AUTO
  contextName: exported
  subjects: [":*:"]
  # subjectRenameFormat: copied-${subject}
