name: ldap
image: osixia/openldap:1.5.0

env:
  LDAP_ORGANISATION: "Confluent Inc."
  LDAP_DOMAIN: "confluent.io"
  LDAP_ADMIN_PASSWORD: "confluentrox"
  LDAP_CONFIG_PASSWORD: "confluentconfigrox"
  LDAP_READONLY_USER: "true"
  LDAP_READONLY_USER_USERNAME: "mds"
  LDAP_READONLY_USER_PASSWORD: "Developer!"
  LDAP_BASE_DN: "DC=admin,DC=confluent,DC=io"

# Adding integer before ldif name to allow sequence order.
ldifs:
  00_groups.ldif: |-
    dn: OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: Accounts

    dn: OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: Accounts

    dn: OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: HP

    dn: OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: Privileged

    dn: OU=Groups,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: Groups

    dn: OU=Roles,OU=Groups,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: Roles
  01_kafka.ldif: |-
    dn: cn=kafka,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: kafka-secret
    description: kafka user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: kafka
  02_erp.ldif: |-
    dn: cn=erp,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: erp-secret
    description: erp user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: erp
  03_sr.ldif: |-
    dn: cn=sr,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: sr-secret
    description: schema registry user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: sr
  04_c3.ldif: |-
    dn: cn=c3,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: c3-secret
    description: control center user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: c3
  05_ksql.ldif: |-
    dn: cn=ksql,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: ksql-secret
    description: ksql user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: ksql
  06_connect.ldif: |-
    dn: cn=connect,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: connect-secret
    description: connect user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: connect
  07_replicator.ldif: |-
    dn: cn=replicator,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: replicator-secret
    description: replicator user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: replicator
  08_krp.ldif: |-
    dn: cn=krp,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: krp-secret
    description: krp user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: krp
  09_c3-test.ldif: |-
    dn: cn=testadmin,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: testadmin
    description: testadmin user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: testadmin
  10_c3usersgroup.ldif: |-
    dn: cn=c3users,OU=Roles,OU=Groups,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: top
    objectClass: posixGroup
    cn: c3users
    gidNumber: 5000
  11_readonlyusersgroup.ldif: |-
    dn: cn=readonlyusers,OU=Roles,OU=Groups,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: top
    objectClass: posixGroup
    cn: readonlyusers
    gidNumber: 5000
  12_alice.ldif:  |-
    dn: cn=alice,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    uid: alice
    sn: LookingGlass
    givenName: Alice
    cn: alice
    displayName: Alice LookingGlass
    uidNumber: 10000
    gidNumber: 5000
    userPassword: alice-secret
    gecos: alice
    loginShell: /bin/bash
    homeDirectory: /home/alice
  13_james.ldif:  |-
    dn: cn=james,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    uid: james
    sn: LookingGlass
    givenName: James
    cn: james
    displayName: James Logan
    uidNumber: 10009
    gidNumber: 5000
    userPassword: james-secret
    gecos: james
    loginShell: /bin/bash
    homeDirectory: /home/james
  14_addgroup.ldif:  |-
    dn: cn=readonlyusers,OU=Roles,OU=Groups,OU=RBAC,{{ LDAP_BASE_DN }}
    changetype: modify
    add: memberuid
    memberuid: cn=alice,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}

    dn: cn=c3users,OU=Roles,OU=Groups,OU=RBAC,{{ LDAP_BASE_DN }}
    changetype: modify
    add: memberuid
    memberuid: cn=james,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
  15_kafka-dev.ldif: |-
    dn: cn=devuser,OU=Privileged,OU=HP,OU=Accounts,OU=RBAC,{{ LDAP_BASE_DN }}
    userPassword: dev-password
    description: Developer user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: devuser
    
tls:
  enabled: true
  fullchain: |
    -----BEGIN CERTIFICATE-----
    MIIEgDCCA2igAwIBAgIUBQ89KVpRG+C1RnkCgKCbsaK90rUwDQYJKoZIhvcNAQEL
    BQAwaTELMAkGA1UEBhMCVVMxEjAQBgNVBAgTCVBhbG8gQWx0bzELMAkGA1UEBxMC
    Q0ExEjAQBgNVBAoTCUNvbmZsdWVudDEUMBIGA1UECxMLRW5naW5lZXJpbmcxDzAN
    BgNVBAMTBlRlc3RDQTAeFw0yMDAzMTgxOTMzMDBaFw0yNTAzMTcxOTMzMDBaMD4x
    CzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTESMBAGA1UEBxMJUGFsbyBBbHRvMQ4w
    DAYDVQQDEwVrYWZrYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANGG
    GOdK/BUjwdJ+DCiQiAVnzWq3ftiM8vg38799TEAU51CF0Z18pRt3YuWd144h7oT1
    efxJ34YyUOKbEc2hl7VlUjX8VILQ88EpnuB5eKIlqcCWPHE3ucqQ87G5ZHQnrLNC
    mbKQw6TwjHEztItehXS1u7R+AC+RWj4DX9spwEQvIPnQvE/cJmYVldrXySzb9YOJ
    OJ8qdRPAbbOslf1RJyVb+NJkzQryLn8ZCB64gzLjUfKE7nXM49nUdSJFugye+RGt
    1BPpYHQUZfJY0nrRLhyqIE63mlJftRNMNYroO0a6lfLLXUCAifFxcvm2OGxkrWFl
    uYtbR0FCacFzS6gJw08CAwEAAaOCAUkwggFFMA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUv+RLr0E14tfl+dnZCI4PsV5cx5cwHwYDVR0jBBgwFoAUP120AJVtt227bZRr
    0nAfb6qEAhQwgcUGA1UdEQSBvTCBuoInKi5wbGF0Zm9ybW9wcy5kZXYuZ2NwLmRl
    dmVsLmNwZGV2LmNsb3Vkgg8qLmNsdXN0ZXIubG9jYWyCEyouc3ZjLmNsdXN0ZXIu
    bG9jYWyCHCoub3BlcmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWyCIioua2Fma2Eub3Bl
    cmF0b3Iuc3ZjLmNsdXN0ZXIubG9jYWyCJyoucmVwbGljYXRvci5vcGVyYXRvci5z
    dmMuY2x1c3Rlci5sb2NhbDANBgkqhkiG9w0BAQsFAAOCAQEA8vNmq0EzYHJEsBqX
    5i7Yo0cNcVvNbLtX8C7iUNJ9kJC3nUi8iWZLtsvfI2aNAvqNe6x+4rOUxZ1BBiGL
    dPubLkaE4kqJRnPY66FQMFlRnP+yIzefWCN03JY6c4+AUhWUgz21kvFv6Za5HH3I
    W5r+vUSVOcvB414H36zjEwU/xJHW9XP+ILbzkG6LxB39qSSb1VtHpLEt94WPfa7u
    Py3LhAbPo4O6emE/XPpP18sYyX37p9bIlPmoQdZ4MXhQQyo4PNuIbGZpROZgCXVZ
    0Ztcp8BvRGPMF43tsK6paiD4UZgbcXkC73QQxZGcG6b7IaOIGuDavuu/pnsfumZD
    DuKNsA==
    -----END CERTIFICATE-----
  privkey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA0YYY50r8FSPB0n4MKJCIBWfNard+2Izy+Dfzv31MQBTnUIXR
    nXylG3di5Z3XjiHuhPV5/EnfhjJQ4psRzaGXtWVSNfxUgtDzwSme4Hl4oiWpwJY8
    cTe5ypDzsblkdCess0KZspDDpPCMcTO0i16FdLW7tH4AL5FaPgNf2ynARC8g+dC8
    T9wmZhWV2tfJLNv1g4k4nyp1E8Bts6yV/VEnJVv40mTNCvIufxkIHriDMuNR8oTu
    dczj2dR1IkW6DJ75Ea3UE+lgdBRl8ljSetEuHKogTreaUl+1E0w1iug7RrqV8std
    QICJ8XFy+bY4bGStYWW5i1tHQUJpwXNLqAnDTwIDAQABAoIBAAYZlVgGgthKtjXe
    nZQAwTUHFJ/qv7KmR9yaJGqKx1GGSkW536RqIJRwIVz1/3SP4FXWn7qMnAlYJaqz
    QQ1viu8pB/+yXPOCCdax04JNhwmRdyO4PAI/0RToq2+dKiOHlCuT4M2mEUwYBL62
    9qaoFdKUB+b1VCQOY0Yy6vOCf6p8d0hR7rWI3j/7r5yMRR0E150HTeNNNMPeqdfT
    VLv48cL73zMo3/WStDr98/2Lrt7Hodx3PA4cJCbWei077bjoSQbDpmtRlNHFxADH
    p4RXSMQBVDhC/ojB94C5WITd87xufqBlGATcsvTtDGrdXqLhlu5mlD1dIF6R/L56
    UfIOFaECgYEA7FvnJgFpawahFLJFepR9uSq4FhQhpesNCbP1HOwS2sQz/LNFiXYq
    o7XdxoiUtBkaL8UryIkkGK7Hja8NwQgOoClcQV2XSWDhjjuEgGGy1tFg27aZivz/
    68ltsGFuqMcTAjHh3b2pWu/+Hx0HxA0paXL7zMKsj3smTLyVCywv8UUCgYEA4u9T
    ceIYD4TDc7W8e4EHNR52lIIIQ3nRNx6v4loB9Oi4D5J//GjzTvx15EUk05m3351e
    cfQlidRKfLAeWgvO4VqK1wKHvYjsTF7by2PhApfAYeYK5pQZcfvvhwMJ3D3hIQ0o
    xY4DwMREdJyTazbzGyT0CTxseQWo0UidyuYcaYMCgYEAjmUz1e7FzufYhbp9J0Ns
    lvDIpOyN9QKuASl8w2bqWQgZdeWfQBiDyctYiDJivDnfT+ZO4WrV51Ts/kv3UlMD
    VLR2Ux8KdPe8C8+JnTq+3rKX0uaojFat7CSXQ8r/OwlsR0c8FzYbYKDzjVUVB6US
    TOgsEQk7otmDknmOpYOCgq0CgYEAttyUh9rg+nhHqpCR7Y8eCK6gbLCPChg5/slq
    fuF6XCe+UUYCfZjwHgCO2r7gmuVt5fF/7iEGspZu4yRjgLmtHagA4pp2WMLhbfSt
    9alo4db4ParJs90418Fj1I4dPuxZ4XEiHnZ+DbHZW4HjxGwF3ySaxGp9GdP2oZV7
    GMjtshMCgYBWU8d5+rl1WKrlzWp0wKDtE4xNEPFWdtW8Q5QuAzom5FFbALvtmumT
    4ilud9tjcUkjBm/ZgKfrRnoEE8GMa3MJfmsXRHOcCK7VREC/qe6TrjdAnmorETaQ
    IewPgaFUGIsw5+QOdMWVZlHCcDN1z6ipeLKM/iZWm0nDAEzntoayFw==
    -----END RSA PRIVATE KEY-----
  cacerts: |
    -----BEGIN CERTIFICATE-----
    MIIDojCCAoqgAwIBAgIUP7i11Hoa6d1fDRT2LlTm307kkQ4wDQYJKoZIhvcNAQEL
    BQAwaTELMAkGA1UEBhMCVVMxEjAQBgNVBAgTCVBhbG8gQWx0bzELMAkGA1UEBxMC
    Q0ExEjAQBgNVBAoTCUNvbmZsdWVudDEUMBIGA1UECxMLRW5naW5lZXJpbmcxDzAN
    BgNVBAMTBlRlc3RDQTAeFw0xOTAyMDIwNDUxMDBaFw0yNDAyMDEwNDUxMDBaMGkx
    CzAJBgNVBAYTAlVTMRIwEAYDVQQIEwlQYWxvIEFsdG8xCzAJBgNVBAcTAkNBMRIw
    EAYDVQQKEwlDb25mbHVlbnQxFDASBgNVBAsTC0VuZ2luZWVyaW5nMQ8wDQYDVQQD
    EwZUZXN0Q0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD11Fyc1C5c
    WiRipay6P5yzS/h1yzDFdV+eHvFp0KJn74hgb6LtREB1fmwxzBQDDa2DIGwLa/7u
    m336ZgE9cPz1aRB7a9sQX9EU84sDKL7WhJkabtkZvS4LxwWkchiaSWiTV72E4zWS
    jUBPaeTsE2NFG89uPOVl+TKPNkRpyAfCYrUTGlxcCZ9YbJolGRbvdQB6HtbCut+m
    TnUO/5jHBvkjz4uQEF9m5MYEaWYPLlUL7qZxy0pQshtdgt3+R8BWifjKsg5XGKbE
    fwrOlpQ30vWOIb4uEGmO+nNJCdoe56IBEsUyNh1HiugBqxqKg2Q1GnHCQCGFiZJW
    kGO6ptOQDSGjAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTAD
    AQH/MB0GA1UdDgQWBBQ/XbQAlW23bbttlGvScB9vqoQCFDANBgkqhkiG9w0BAQsF
    AAOCAQEAWaw1FSgKnE7qKYurh5enK1YUd5qNTn5HLph+bAbXWUxzoU/Tn3omtPiU
    dYY+pO0lebIiB/1HTQMNIVklHbf+TTlOqf3BADDrA1rioish/NO5xo0b3aNaoLWC
    UIcq3qZnpT/KEFKf3MV/ZSvV6xYHcPfqffEzB3xj1Tv33wIVOajoekyYZERgokIL
    Qk8GlirDNwzq9lUjAu+bxBptKdyNk2ms0fuE7g55uJ+5auStmVVytGGa3usbROOq
    afaRd3LdUKjlLD1rMlyHyL1dwvmdk7duNuEFVbEavFaItIDv9YHJYVXUU+HraLk/
    deV0pNzJwC651CXsW76y1QEVWxh4mw==
    -----END CERTIFICATE-----
