apiVersion: v1
kind: Pod
metadata:
  name: kcat
  namespace: confluent
spec:
  containers:
  - name: cp-kcat
    image: confluentinc/cp-kcat:8.1.0
    command: ['sh', '-c', 'tail -f /dev/null']
    volumeMounts:
      - name: tls-certs
        mountPath: /mnt/certs
        readOnly: true
      - name: kcat-configs
        mountPath: /mnt/configs        
        readOnly: true
  volumes:
    - name: tls-certs
      secret:
        secretName: tls-client
    - name: kcat-configs
      configMap:
        defaultMode: 420
        name: kcat-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kcat-config
  namespace: confluent
data:
  kcat-plain.conf: |
    bootstrap.servers=kafka.confluent.svc.cluster.local:9092
    security.protocol=SASL_PLAINTEXT
    sasl.mechanisms=PLAIN
    sasl.username=kafka
    sasl.password=kafka-secret
  kcat-plain-tls.conf: |
    bootstrap.servers=kafka.confluent.svc.cluster.local:9092
    security.protocol=SASL_SSL
    ssl.ca.location=/mnt/certs/ca.crt
    sasl.mechanisms=PLAIN
    sasl.username=kafka
    sasl.password=kafka-secret
  kcat-mtls.conf: |
    bootstrap.servers=kafka.confluent.svc.cluster.local:9092
    security.protocol=SSL
    ssl.ca.location=/mnt/certs/ca.crt
    ssl.key.location=/mnt/certs/tls.key
    ssl.key.password=changeme
    ssl.certificate.location=/mnt/certs/tls.crt
