---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper-new
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-zookeeper:7.6.1
    init: confluentinc/confluent-init-container:2.8.2
  license:
    globalLicense: true
  dataVolumeCapacity: 1Gi
  logVolumeCapacity: 1Gi
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka-new
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server:7.6.1
    init: confluentinc/confluent-init-container:2.8.2
  license:
    globalLicense: true
  dataVolumeCapacity: 1Gi
  dependencies:
    zookeeper:  
      endpoint: zookeeper-new.confluent.svc.cluster.local:2181
  configOverrides:
    server:
      - offsets.topic.replication.factor=1
      - password.encoder.secret=encoder-secret
      - transaction.state.log.replication.factor=1
      - confluent.license.topic.replication.factor=1
      - confluent.metadata.topic.replication.factor=1
      - confluent.balancer.topic.replication.factor=1
      - confluent.metrics.reporter.topic.replicas=1
      - confluent.security.event.logger.exporter.kafka.topic.replicas=1
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: kafka-new-rest
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka-new
  kafkaRest:
    endpoint: http://kafka-new.confluent.svc.cluster.local:8090
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry-new
  namespace: confluent
spec:
  replicas: 1
  enableSchemaExporter: true
  image:
    application: confluentinc/cp-schema-registry:7.6.1
    init: confluentinc/confluent-init-container:2.8.2
  license:
    globalLicense: true
  dependencies:
    kafka:  
      bootstrapEndpoint: kafka-new.confluent.svc.cluster.local:9071
