apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic-new
  namespace: confluent
spec:
  name: test-topic
  replicas: 1
  partitionCount: 6
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka-new
    namespace: confluent